# Welcome to Jekyll!

# Website settings
title: "上海鲲鹏信息科技有限公司"
description: "上海鲲鹏信息科技有限公司"
keywords: "上海, 鲲鹏, 外包, 服务, 网站, 开发, KP"
baseurl: "/"
url: "http://www.shrocit.com"
# url: "http://127.0.0.1:4000"
